name: Build All Linux

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-arch:
    uses: ./.github/workflows/build-linux-arch.yml

  build-debian:
    uses: ./.github/workflows/build-linux-debian.yml

  # build-fedora:
  #   uses: ./.github/workflows/build-linux-fedora.yml
